### ISSUE TITLE
'explore' button breaks intermittently when gambling on stone or iron

### ISSUE THREAD

**Issue by marquisdan** [saltytext/wg#13]
Issue occurred in Google chrome Version 41.0.2272.101 m
Reproduction steps:
Either explore til you find stone or use the collection link til you find stone or iron.
Just keep clicking yes
If you get the 'you have destroyed some of the X' the explore button doesn't seem to work.

Seems to work fine if all the stone/iron is destroyed.

**Comment by saltytext** [comment]
SyntaxError: missing ] after element list
issue was related to a ; added incorrectly.

will be resolved in v0.0.16
